import { SIDE, H, getTriVertices, type TriType } from "@/lib/grid-math";

/**
 * Rectangular export crop, constrained to the triangular lattice.
 *
 * The tiling's translation symmetries are generated by
 *
 *   u = (SIDE, 0)     -> (q, r) becomes (q+1, r)
 *   v = (SIDE/2, H)   -> (q, r) becomes (q, r+1)
 *
 * An *axis-aligned* rectangle only repeats by pure horizontal/vertical
 * translation if its periods are themselves axis-aligned members of that group:
 *
 *   horizontal: a*u + b*v with b*H = 0  =>  b = 0     =>  width  = m * SIDE
 *   vertical:   a*SIDE + b*SIDE/2 = 0   =>  b = 2n    =>  height = n * 2H
 *                                           (because (0, 2H) = 2v - u)
 *
 * So the crop is four integers: an anchor expressed as the lattice vector
 * i*u + j*v, and tile counts m x n. Every reachable rectangle is therefore an
 * exact repeat unit — the grid lines continue across a tile seam. That is a
 * statement about the *lattice*, not the artwork: arbitrary painting only
 * repeats seamlessly if it was painted periodically.
 */
export interface CropRect {
  /** Anchor along u = (SIDE, 0). */
  i: number;
  /** Anchor along v = (SIDE/2, H). */
  j: number;
  /** Tile count horizontally; width = m * SIDE. */
  m: number;
  /** Tile count vertically; height = n * 2H. */
  n: number;
}

export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

/** Vertical period of the lattice: (0, 2H) = 2v - u. */
export const V_PERIOD = 2 * H;

/** Roughly square and centred on the origin: x -100..100, y -86.6..86.6. */
export const DEFAULT_CROP: CropRect = { i: -1, j: -2, m: 4, n: 2 };

/** World-space bounds of a crop. Always axis-aligned in world space. */
export function cropWorldBounds(c: CropRect): Rect {
  return {
    x: c.i * SIDE + c.j * (SIDE / 2),
    y: c.j * H,
    w: c.m * SIDE,
    h: c.n * V_PERIOD,
  };
}

/**
 * Bounds after the display rotation `screen = center + zoom * R(theta) * (world + view)`.
 * theta is only ever 0 or PI/2, and a quarter turn maps an axis-aligned rect to
 * an axis-aligned rect — so this is exact, and at PI/2 the dimensions swap.
 * Exports use these bounds so the file matches what is on screen.
 */
export function cropDisplayBounds(c: CropRect, gridRotation: number): Rect {
  const { x, y, w, h } = cropWorldBounds(c);
  if (!gridRotation) return { x, y, w, h };
  const cos = Math.cos(gridRotation);
  const sin = Math.sin(gridRotation);
  const xs: number[] = [];
  const ys: number[] = [];
  for (const [px, py] of [
    [x, y],
    [x + w, y],
    [x, y + h],
    [x + w, y + h],
  ]) {
    xs.push(cos * px - sin * py);
    ys.push(sin * px + cos * py);
  }
  const minX = Math.min(...xs);
  const minY = Math.min(...ys);
  return { x: minX, y: minY, w: Math.max(...xs) - minX, h: Math.max(...ys) - minY };
}

/** Rotates a world point into display space. Exact at the only angles used (0, PI/2). */
export function rotatePoint(
  x: number,
  y: number,
  gridRotation: number,
): [number, number] {
  if (!gridRotation) return [x, y];
  const cos = Math.cos(gridRotation);
  const sin = Math.sin(gridRotation);
  return [cos * x - sin * y, sin * x + cos * y];
}

/** Snaps a world point to the nearest lattice anchor (i, j). */
export function worldToAnchor(x: number, y: number): { i: number; j: number } {
  const j = Math.round(y / H);
  const i = Math.round((x - j * (SIDE / 2)) / SIDE);
  return { i, j };
}

/**
 * Smallest crop covering every painted trixel. Used by "Fit to artwork" and as
 * the initial value for a document that already has content.
 */
export function fitCropToPainted(painted: Record<string, string>): CropRect | null {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  let any = false;

  for (const key of Object.keys(painted)) {
    const parts = key.split(",");
    if (parts.length !== 3) continue;
    const q = parseInt(parts[0]);
    const r = parseInt(parts[1]);
    const verts = getTriVertices(q, r, parts[2] as TriType);
    for (const v of verts) {
      if (v.x < minX) minX = v.x;
      if (v.y < minY) minY = v.y;
      if (v.x > maxX) maxX = v.x;
      if (v.y > maxY) maxY = v.y;
    }
    any = true;
  }

  if (!any) return null;

  // Expand outward to whole lattice steps. j is the vertical anchor in units of
  // H, but the height must be a whole number of 2H — so the anchor is floored to
  // H and the count rounded up from there.
  const j = Math.floor(minY / H);
  const i = Math.floor((minX - j * (SIDE / 2)) / SIDE);
  const x0 = i * SIDE + j * (SIDE / 2);
  const y0 = j * H;
  const m = Math.max(1, Math.ceil((maxX - x0) / SIDE));
  const n = Math.max(1, Math.ceil((maxY - y0) / V_PERIOD));
  return { i, j, m, n };
}

export type CropHandle =
  | "nw"
  | "n"
  | "ne"
  | "e"
  | "se"
  | "s"
  | "sw"
  | "w"
  | "move";

/** Handle centres in world space, keyed by handle name. */
export function handlePositions(c: CropRect): Array<{ handle: CropHandle; x: number; y: number }> {
  const { x, y, w, h } = cropWorldBounds(c);
  const cx = x + w / 2;
  const cy = y + h / 2;
  return [
    { handle: "nw", x, y },
    { handle: "n", x: cx, y },
    { handle: "ne", x: x + w, y },
    { handle: "e", x: x + w, y: cy },
    { handle: "se", x: x + w, y: y + h },
    { handle: "s", x: cx, y: y + h },
    { handle: "sw", x, y: y + h },
    { handle: "w", x, y: cy },
  ];
}

/**
 * Which handle a world point grabs, or "move" when inside the rect, or null.
 * Corners are tested before edges so the overlap at a corner favours resizing
 * both axes.
 */
export function hitTestHandle(
  c: CropRect,
  wx: number,
  wy: number,
  tol: number,
): CropHandle | null {
  const positions = handlePositions(c);
  const corners = positions.filter((p) => p.handle.length === 2);
  const edges = positions.filter((p) => p.handle.length === 1);
  for (const p of [...corners, ...edges]) {
    if (Math.abs(wx - p.x) <= tol && Math.abs(wy - p.y) <= tol) return p.handle;
  }
  const { x, y, w, h } = cropWorldBounds(c);
  if (wx >= x && wx <= x + w && wy >= y && wy <= y + h) return "move";
  return null;
}

/**
 * Applies a world-space drag delta to a crop, snapping to whole lattice steps.
 *
 * Anchors move along the lattice basis (u, v); edges move in whole periods of
 * SIDE / 2H. An edge dragged past its opposite re-anchors instead of producing a
 * negative extent, so the rect stays valid without the pointer having to stop.
 */
export function applyCropDrag(
  start: CropRect,
  handle: CropHandle,
  dx: number,
  dy: number,
): CropRect {
  if (handle === "move") {
    // A pure translation must stay on the lattice, so the delta is resolved
    // against (u, v) rather than being snapped per-axis.
    const dj = Math.round(dy / H);
    const di = Math.round((dx - dj * (SIDE / 2)) / SIDE);
    return { ...start, i: start.i + di, j: start.j + dj };
  }

  let { i, j, m, n } = start;

  if (handle.includes("w")) {
    // The left edge moves along u only: shifting i changes x without touching y.
    const di = Math.round(dx / SIDE);
    i += di;
    m -= di;
  } else if (handle.includes("e")) {
    m += Math.round(dx / SIDE);
  }

  if (handle.startsWith("n")) {
    // The top edge moves by whole 2H steps, and (0, 2H) = 2v - u — so j gains
    // 2 per step and i must lose 1 to hold x still.
    const dn = Math.round(dy / V_PERIOD);
    j += 2 * dn;
    i -= dn;
    n -= dn;
  } else if (handle.startsWith("s")) {
    n += Math.round(dy / V_PERIOD);
  }

  // Flip rather than invert: an edge dragged past its opposite mirrors the rect
  // about that opposite edge, which is what every other crop UI does. The
  // opposite edge is invariant under the naive update above, so re-anchoring to
  // it is the same expression for a west drag and an east drag.
  if (m < 1) {
    i = i + m;
    m = Math.max(1, -m);
  }
  if (n < 1) {
    i = i - n;
    j = j + 2 * n;
    n = Math.max(1, -n);
  }

  return { i, j, m, n };
}
